query ($userId: String) {
  published_form(where: {userId: {_eq: $userId}}) {
    id
    name
    headline
    tagline
    buttonBackgroundColor
    buttonText
    buttonTextColor
    campaignId
  }
}
